require('dotenv').config();
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Avvio seeding database Roxanne L.68/99...');

  // 1. Inserimento dei 20 Cittadini / Iscritti L.68/99 realistici
  const ventiPersone = [
    {
      numeroIscrizione: 10452,
      codice: 'PERS-10452',
      nome: 'Mario',
      cognome: 'Rossi',
      codiceFiscale: 'RSSMRA78A01E507X',
      dataNascita: new Date('1978-01-15'),
      natoA: 'Lecco',
      sesso: 'M',
      statoCivile: 'Coniugato/a',
      comuneResidenza: 'Lecco',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Roma 45',
      domicilioComune: 'Lecco',
      domicilioProvincia: 'LC',
      domicilioIndirizzo: 'Via Roma 45',
      cellulare: '3389876543',
      telefono: '0341123456',
      email: 'mario.rossi@email.it',
      patente: 'B',
      categoria: 'C.O.',
      categoriaLg6869: 'Disabili Fisici (Art. 1)',
      dataIscrizioneCO: new Date('2018-03-10'),
      dataIscrizioneLista: new Date('2018-03-10'),
      attivoNonAttivo: 'Attivo',
      stato: 'Disoccupato',
      disponibile: 'Sì',
      operatore: 'CPI Lecco (M. Galli)',
      icPercentuale: 67,
      diagnosi: 'Esiti poliomielite arto inferiore sinistro con deficit deambulazione prolungata.',
      diagnosiLastDescTipoSupporto: 'Adattamento postazione ergonomica e sedia regolabile con supporto lombare.',
      asl: 'ASST Lecco Ospedale Manzoni',
      patologia: 'Minorazione Motoria Arto Inferiore',
      handicapL104: true,
      allegatiLg68: true,
      titoloStudioLast: 'Diploma di Ragioneria / Perito Commerciale',
      titoloStudioPresso: 'I.T.C. Viganò Merate',
      votazione: '85/100',
      anno: 1997,
      qualifica: 'Ragioniere Programmatore',
      ecdl: 'Sì (Certificato PC)',
      inglese: true,
      stazioneEretta: false,
      movimentazioneManuale: false,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: false,
      contattoPubblico: true,
      impiegato: true,
      impiegatoMansione: 'Contabile Junior / Data Entry',
      receptionSegreteria: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Part-Time Mattina (25-30h)',
          smartWorking: true,
          raggioMaxKm: 25,
          mezzoMunit: true,
          noteDisponibilita: 'Preferenza per sede Lecco o comuni limitrofi raggiungibili in auto.'
        }
      }
    },
    {
      numeroIscrizione: 10453,
      codice: 'PERS-10453',
      nome: 'Laura',
      cognome: 'Bianchi',
      codiceFiscale: 'BNCLRA85C45F133Z',
      dataNascita: new Date('1985-03-05'),
      natoA: 'Merate',
      sesso: 'F',
      statoCivile: 'Celibe/Nubile',
      comuneResidenza: 'Merate',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Garibaldi 12',
      cellulare: '3471122334',
      email: 'laura.bianchi@gmail.com',
      patente: 'B',
      categoria: 'C.O.',
      categoriaLg6869: 'Disabilità Uditiva / Sensoriale',
      dataIscrizioneCO: new Date('2020-05-14'),
      dataIscrizioneLista: new Date('2020-05-14'),
      attivoNonAttivo: 'Attivo',
      stato: 'Disoccupato',
      disponibile: 'Sì',
      operatore: 'CPI Merate (E. Bianchi)',
      icPercentuale: 75,
      diagnosi: 'Ipoacusia bilaterale profonda con protesizzazione acustica.',
      diagnosiLastDescTipoSupporto: 'Postazione in ambiente silenzioso o con notifiche visive al computer.',
      asl: 'ASST Lecco Ospedale Mandic Merate',
      patologia: 'Deficit Uditivo Bilaterale',
      handicapL104: true,
      allegatiLg68: true,
      titoloStudioLast: 'Laurea in Lingue e Letterature Straniere',
      titoloStudioPresso: 'Università degli Studi di Bergamo',
      votazione: '105/110',
      anno: 2009,
      qualifica: 'Traduttrice / Redattrice Testi',
      ecdl: 'Sì (Certificato PC)',
      inglese: true,
      francese: true,
      spagnolo: true,
      stazioneEretta: true,
      movimentazioneManuale: true,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: false,
      colonna: true,
      contattoPubblico: false,
      impiegato: true,
      impiegatoMansione: 'Traduttrice / Redazione e Corrispondenza Estero',
      informatica: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Full-Time (40h)',
          smartWorking: true,
          raggioMaxKm: 20,
          mezzoMunit: true,
          noteDisponibilita: 'Ottime capacità scritte in 3 lingue europee.'
        }
      }
    },
    {
      numeroIscrizione: 10454,
      codice: 'PERS-10454',
      nome: 'Giuseppe',
      cognome: 'Colombo',
      codiceFiscale: 'CLMGPP68D12A745Y',
      dataNascita: new Date('1968-04-12'),
      natoA: 'Calolziocorte',
      sesso: 'M',
      statoCivile: 'Coniugato/a',
      comuneResidenza: 'Calolziocorte',
      residenzaProvincia: 'LC',
      indirizzo: 'Corso Dante 8',
      cellulare: '3334567890',
      patente: 'B, C',
      categoria: 'C.O.',
      categoriaLg6869: 'Disabilità Motoria e Articolare',
      dataIscrizioneCO: new Date('2019-11-03'),
      attivoNonAttivo: 'Attivo',
      stato: 'Occupato (T.Det)',
      disponibile: 'Sì',
      operatore: 'CPI Lecco (M. Galli)',
      icPercentuale: 55,
      diagnosi: 'Gonalgia cronica bilaterale con limitazione funzionale agli arti inferiori.',
      asl: 'ASST Lecco Ospedale Manzoni',
      patologia: 'Artrosi Ginocchia e Colonna Vertebrale',
      handicapL104: false,
      allegatiLg68: true,
      titoloStudioLast: 'Qualifica Professionale Meccanica',
      titoloStudioPresso: 'C.F.P. Lecco',
      anno: 1986,
      qualifica: 'Operatore Macchine Utensili CNC',
      stazioneEretta: false,
      movimentazioneManuale: false,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: false,
      contattoPubblico: false,
      artigiano: true,
      impiegato: false,
      disponibilita: {
        create: {
          orarioPreferito: 'Part-Time Mattina (20-25h)',
          raggioMaxKm: 15,
          mezzoMunit: true,
          noteDisponibilita: 'Esperto su torni e frese con postazione a sedere.'
        }
      }
    },
    {
      numeroIscrizione: 10455,
      codice: 'PERS-10455',
      nome: 'Federica',
      cognome: 'Villa',
      codiceFiscale: 'VLLFRC92M58E507V',
      dataNascita: new Date('1992-08-18'),
      natoA: 'Lecco',
      sesso: 'F',
      statoCivile: 'Celibe/Nubile',
      comuneResidenza: 'Mandello del Lario',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Manzoni 21',
      cellulare: '3495544332',
      email: 'federica.villa92@yahoo.it',
      patente: 'B',
      categoria: 'Art. 18',
      categoriaLg6869: 'Orfani / Figli Vittime Dovere',
      dataIscrizioneCO: new Date('2021-02-10'),
      attivoNonAttivo: 'Attivo',
      stato: 'In Tirocinio',
      disponibile: 'Sì',
      operatore: 'CPI Lecco (R. Rossi)',
      icPercentuale: 0,
      asl: 'ASST Lecco',
      patologia: 'Art. 18 Categorie Protette',
      titoloStudioLast: 'Diploma Istituto Tecnico per il Turismo',
      titoloStudioPresso: 'Istituto Parini Lecco',
      votazione: '90/100',
      anno: 2011,
      qualifica: 'Accoglienza Turistica e Front Office',
      ecdl: 'Sì (Certificato PC)',
      inglese: true,
      tedesco: true,
      stazioneEretta: true,
      movimentazioneManuale: true,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: true,
      contattoPubblico: true,
      impiegato: true,
      receptionSegreteria: true,
      cassa: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Full-Time (40h)',
          smartWorking: false,
          raggioMaxKm: 25,
          mezzoMunit: true,
          disponibileTurni: true,
          noteDisponibilita: 'Disponibile per strutture alberghiere e uffici turistici.'
        }
      }
    },
    {
      numeroIscrizione: 10456,
      codice: 'PERS-10456',
      nome: 'Alessandro',
      cognome: 'Brambilla',
      codiceFiscale: 'BRMLSN88T10F133W',
      dataNascita: new Date('1988-12-10'),
      natoA: 'Merate',
      sesso: 'M',
      statoCivile: 'Celibe/Nubile',
      comuneResidenza: 'Casatenovo',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Volta 14',
      cellulare: '3318765432',
      email: 'alessandro.brambilla@outlook.it',
      patente: 'B, Muletto',
      patenteMuletto: true,
      categoria: 'C.O.',
      categoriaLg6869: 'Disabilità Psichica Lieve',
      dataIscrizioneCO: new Date('2017-09-01'),
      attivoNonAttivo: 'Attivo',
      stato: 'Disoccupato',
      disponibile: 'Sì',
      operatore: 'CPI Merate (E. Bianchi)',
      icPercentuale: 60,
      diagnosi: 'Disturbo d\'ansia generalizzato e fobia sociale controllata da terapia.',
      diagnosiLastDescTipoSupporto: 'Compiti strutturati con routine definita ed evitare contatto diretto con pubblico numeroso.',
      asl: 'ASST Lecco CPS Merate',
      patologia: 'Disturbo dell\'Umore / Ansia',
      titoloStudioLast: 'Diploma Tecnico Grafica e Comunicazione',
      anno: 2007,
      qualifica: 'Operatore Grafico / Magazziniere',
      stazioneEretta: true,
      movimentazioneManuale: true,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: true,
      contattoPubblico: false,
      magazzino: true,
      informatica: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Part-Time Mattina (20-25h)',
          raggioMaxKm: 15,
          mezzoMunit: true,
          noteDisponibilita: 'Precisione meticolosa nella gestione scorte e archivi.'
        }
      }
    },
    {
      numeroIscrizione: 10457,
      codice: 'PERS-10457',
      nome: 'Simona',
      cognome: 'Crippa',
      codiceFiscale: 'CRPSMN74P60E507L',
      dataNascita: new Date('1974-09-20'),
      natoA: 'Lecco',
      sesso: 'F',
      statoCivile: 'Separato/a',
      comuneResidenza: 'Oggiono',
      residenzaProvincia: 'LC',
      indirizzo: 'Piazza Manzoni 3',
      cellulare: '3409871234',
      email: 'simona.crippa74@libero.it',
      patente: 'B',
      categoria: 'C.O.',
      categoriaLg6869: 'Disabilità Motoria',
      dataIscrizioneCO: new Date('2019-04-18'),
      attivoNonAttivo: 'Attivo',
      stato: 'Disoccupato',
      disponibile: 'Sì',
      operatore: 'CPI Lecco (M. Galli)',
      icPercentuale: 80,
      diagnosi: 'Sclerosi multipla forma recidivante-remittente in fase di stabilità.',
      diagnosiLastDescTipoSupporto: 'Richiesto smart working parziale e assenza di carichi pesanti.',
      asl: 'ASST Lecco Ospedale Manzoni',
      patologia: 'Sclerosi Multipla',
      handicapL104: true,
      allegatiLg68: true,
      titoloStudioLast: 'Laurea in Economia e Commercio',
      titoloStudioPresso: 'Università Cattolica Milano',
      votazione: '108/110',
      anno: 1999,
      qualifica: 'Specialista Amministrazione e Controllo di Gestione',
      ecdl: 'Sì (Certificato PC)',
      inglese: true,
      francese: false,
      stazioneEretta: false,
      movimentazioneManuale: false,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: false,
      contattoPubblico: true,
      impiegato: true,
      impiegatoMansione: 'Contabilità Avanzata / Bilancio / SAP',
      receptionSegreteria: false,
      disponibilita: {
        create: {
          orarioPreferito: 'Part-Time Mattina (20-25h)',
          smartWorking: true,
          raggioMaxKm: 20,
          mezzoMunit: true,
          noteDisponibilita: 'Profilo altamente qualificato per aree amministrative e finanziarie.'
        }
      }
    },
    {
      numeroIscrizione: 10458,
      codice: 'PERS-10458',
      nome: 'Davide',
      cognome: 'Riva',
      codiceFiscale: 'RVIDVD95A15A745M',
      dataNascita: new Date('1995-01-15'),
      natoA: 'Calolziocorte',
      sesso: 'M',
      statoCivile: 'Celibe/Nubile',
      comuneResidenza: 'Valmadrera',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Roma 100',
      cellulare: '3391234876',
      email: 'davide.riva.dev@gmail.com',
      patente: 'B',
      categoria: 'C.O.',
      categoriaLg6869: 'Disabilità Motoria Arto Superiore',
      dataIscrizioneCO: new Date('2022-01-10'),
      attivoNonAttivo: 'Attivo',
      stato: 'Disoccupato',
      disponibile: 'Sì',
      operatore: 'CPI Lecco (R. Rossi)',
      icPercentuale: 48,
      diagnosi: 'Esiti trauma plesso brachiale destro con lieve ipostenia arto destro.',
      asl: 'ASST Lecco Ospedale Manzoni',
      patologia: 'Lesione Plesso Brachiale',
      titoloStudioLast: 'Laurea Triennale in Informatica',
      titoloStudioPresso: 'Università degli Studi di Milano Bicocca',
      votazione: '100/110',
      anno: 2018,
      qualifica: 'Sviluppatore Software Web / Fullstack',
      ecdl: 'Sì (Certificato PC)',
      inglese: true,
      stazioneEretta: true,
      movimentazioneManuale: false,
      manualitaFine: true,
      artiSuperiori: false,
      vista: true,
      udito: true,
      colonna: true,
      contattoPubblico: true,
      impiegato: true,
      informatica: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Full-Time (40h)',
          smartWorking: true,
          raggioMaxKm: 30,
          mezzoMunit: true,
          noteDisponibilita: 'Esperienza in Javascript, Python, database e gestione reti aziendali.'
        }
      }
    },
    {
      numeroIscrizione: 10459,
      codice: 'PERS-10459',
      nome: 'Chiara',
      cognome: 'Panzeri',
      codiceFiscale: 'PNZCHR81H52F133K',
      dataNascita: new Date('1981-06-12'),
      natoA: 'Merate',
      sesso: 'F',
      statoCivile: 'Coniugato/a',
      comuneResidenza: 'Barzanò',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Garibaldi 4',
      cellulare: '3482345678',
      email: 'chiara.panzeri@alice.it',
      patente: 'B',
      categoria: 'F.D.',
      categoriaLg6869: 'Fondo Disabili (F.D.)',
      dataIscrizioneCO: new Date('2016-06-15'),
      attivoNonAttivo: 'Attivo',
      stato: 'Occupato (T.Indet)',
      disponibile: 'No',
      operatore: 'CPI Merate (E. Bianchi)',
      icPercentuale: 70,
      diagnosi: 'Grave deficit visivo bilaterale con residuo visivo ridotto.',
      asl: 'ASST Lecco',
      patologia: 'Retinopatia Degenerativa',
      handicapL104: true,
      titoloStudioLast: 'Diploma Magistrale / Socio-Psico-Pedagogico',
      anno: 2000,
      qualifica: 'Centralinista non vedente / Assistente alla persona',
      ecdl: 'Base',
      stazioneEretta: true,
      movimentazioneManuale: true,
      manualitaFine: true,
      artiSuperiori: true,
      vista: false,
      udito: true,
      colonna: true,
      contattoPubblico: true,
      receptionSegreteria: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Part-Time Mattina (20-25h)',
          smartWorking: true,
          raggioMaxKm: 15,
          mezzoMunit: false,
          noteDisponibilita: 'Abilitata all\'albo nazionale centralinisti non vedenti.'
        }
      }
    },
    {
      numeroIscrizione: 10460,
      codice: 'PERS-10460',
      nome: 'Marco',
      cognome: 'Locatelli',
      codiceFiscale: 'LCTMRC83E15E507Q',
      dataNascita: new Date('1983-05-15'),
      natoA: 'Lecco',
      sesso: 'M',
      statoCivile: 'Celibe/Nubile',
      comuneResidenza: 'Bellano',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Vittorio Veneto 18',
      cellulare: '3356789012',
      patente: 'B',
      categoria: 'C.O.',
      categoriaLg6869: 'Cardiopatia Cronica',
      dataIscrizioneCO: new Date('2020-10-01'),
      attivoNonAttivo: 'Attivo',
      stato: 'Disoccupato',
      disponibile: 'Sì',
      operatore: 'CPI Lecco (M. Galli)',
      icPercentuale: 65,
      diagnosi: 'Cardiopatia ischemica cronica con ridotta tolleranza agli sforzi fisici.',
      asl: 'ASST Lecco Ospedale Manzoni',
      patologia: 'Cardiopatia Ischemica',
      titoloStudioLast: 'Diploma di Maturità Scientifica',
      anno: 2002,
      qualifica: 'Impiegato Ufficio Acquisti',
      ecdl: 'Sì (Certificato PC)',
      inglese: true,
      stazioneEretta: false,
      movimentazioneManuale: false,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: true,
      contattoPubblico: true,
      impiegato: true,
      receptionSegreteria: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Full-Time (40h)',
          smartWorking: true,
          raggioMaxKm: 25,
          mezzoMunit: true,
          noteDisponibilita: 'Vietati sforzi muscolari pesanti e ambienti con sbalzi termici.'
        }
      }
    },
    {
      numeroIscrizione: 10461,
      codice: 'PERS-10461',
      nome: 'Silvia',
      cognome: 'Valsecchi',
      codiceFiscale: 'VLSSLV90B65E507R',
      dataNascita: new Date('1990-02-25'),
      natoA: 'Lecco',
      sesso: 'F',
      statoCivile: 'Celibe/Nubile',
      comuneResidenza: 'Lecco',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Cavour 32',
      cellulare: '3467890123',
      email: 'silvia.valsecchi@fastwebnet.it',
      patente: 'B',
      categoria: 'C.O.',
      categoriaLg6869: 'Disabilità Fisica Arto Inferiore',
      dataIscrizioneCO: new Date('2019-01-20'),
      attivoNonAttivo: 'Attivo',
      stato: 'In Tirocinio',
      disponibile: 'Sì',
      operatore: 'CPI Lecco (M. Galli)',
      icPercentuale: 50,
      diagnosi: 'Esiti frattura complessa bacino con limitata stazione eretta continuata.',
      asl: 'ASST Lecco Ospedale Manzoni',
      patologia: 'Esiti Frattura Bacino',
      titoloStudioLast: 'Diploma Istituto Tecnico Commerciale',
      anno: 2009,
      qualifica: 'Addetta Gestione Ordini e Fatturazione',
      ecdl: 'Sì (Certificato PC)',
      inglese: true,
      stazioneEretta: false,
      movimentazioneManuale: false,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: false,
      contattoPubblico: true,
      impiegato: true,
      cassa: true,
      receptionSegreteria: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Part-Time Mattina (25-30h)',
          smartWorking: false,
          raggioMaxKm: 15,
          mezzoMunit: true,
          noteDisponibilita: 'Ottima presenza ed esperienza pregressa in cassa e accoglienza clienti.'
        }
      }
    },
    {
      numeroIscrizione: 10462,
      codice: 'PERS-10462',
      nome: 'Luca',
      cognome: 'Mauri',
      codiceFiscale: 'MRALCU76L18F133J',
      dataNascita: new Date('1976-07-18'),
      natoA: 'Merate',
      sesso: 'M',
      statoCivile: 'Coniugato/a',
      comuneResidenza: 'Olgiate Molgora',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Sommi Picenardi 11',
      cellulare: '3382345987',
      patente: 'B',
      categoria: 'C.O.',
      categoriaLg6869: 'Disabilità Respiratoria Cronica',
      dataIscrizioneCO: new Date('2018-08-12'),
      attivoNonAttivo: 'Attivo',
      stato: 'Disoccupato',
      disponibile: 'Sì',
      operatore: 'CPI Merate (E. Bianchi)',
      icPercentuale: 60,
      diagnosi: 'BPCO moderata con intolleranza a polveri, fumi e ambienti poco ventilati.',
      asl: 'ASST Lecco',
      patologia: 'Broncopneumopatia Cronica Ostruttiva',
      titoloStudioLast: 'Diploma di Perito Elettronico',
      anno: 1995,
      qualifica: 'Tecnico Riparatore Schede Elettroniche',
      stazioneEretta: true,
      movimentazioneManuale: false,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: true,
      contattoPubblico: false,
      artigiano: true,
      informatica: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Full-Time (40h)',
          raggioMaxKm: 20,
          mezzoMunit: true,
          noteDisponibilita: 'Ambiente di lavoro pulito privo di polveri o vapori chimici.'
        }
      }
    },
    {
      numeroIscrizione: 10463,
      codice: 'PERS-10463',
      nome: 'Sara',
      cognome: 'Castelli',
      codiceFiscale: 'CSTMSRA93P55E507B',
      dataNascita: new Date('1993-09-15'),
      natoA: 'Lecco',
      sesso: 'F',
      statoCivile: 'Celibe/Nubile',
      comuneResidenza: 'Galbiate',
      residenzaProvincia: 'LC',
      indirizzo: 'Via San Rocco 7',
      cellulare: '3478901234',
      email: 'sara.castelli93@gmail.com',
      patente: 'B',
      categoria: 'Art. 18',
      categoriaLg6869: 'Art. 18 Categorie Protette',
      dataIscrizioneCO: new Date('2021-06-01'),
      attivoNonAttivo: 'Attivo',
      stato: 'Disoccupato',
      disponibile: 'Sì',
      operatore: 'CPI Lecco (R. Rossi)',
      icPercentuale: 0,
      asl: 'ASST Lecco',
      patologia: 'Art. 18 Categorie Protette',
      titoloStudioLast: 'Laurea in Scienze della Comunicazione',
      titoloStudioPresso: 'Università degli Studi di Milano',
      votazione: '102/110',
      anno: 2016,
      qualifica: 'Social Media Manager e Copywriter',
      ecdl: 'Sì (Certificato PC)',
      inglese: true,
      francese: true,
      stazioneEretta: true,
      movimentazioneManuale: true,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: true,
      contattoPubblico: true,
      impiegato: true,
      receptionSegreteria: true,
      informatica: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Full-Time (40h)',
          smartWorking: true,
          raggioMaxKm: 30,
          mezzoMunit: true,
          noteDisponibilita: 'Esperienza nella gestione canali digitali, newsletter e ufficio stampa.'
        }
      }
    },
    {
      numeroIscrizione: 10464,
      codice: 'PERS-10464',
      nome: 'Matteo',
      cognome: 'Fontana',
      codiceFiscale: 'FNTMTT80D04A745C',
      dataNascita: new Date('1980-04-04'),
      natoA: 'Calolziocorte',
      sesso: 'M',
      statoCivile: 'Coniugato/a',
      comuneResidenza: 'Calolziocorte',
      residenzaProvincia: 'LC',
      indirizzo: 'Via F.lli Calvi 9',
      cellulare: '3345678901',
      patente: 'B',
      categoria: 'C.O.',
      categoriaLg6869: 'Ernia Discale e Discoptia Lombare',
      dataIscrizioneCO: new Date('2017-03-22'),
      attivoNonAttivo: 'Attivo',
      stato: 'Disoccupato',
      disponibile: 'Sì',
      operatore: 'CPI Lecco (M. Galli)',
      icPercentuale: 46,
      diagnosi: 'Lombosciatalgia cronica recidivante con divieto di movimentazione carichi pesanti.',
      asl: 'ASST Lecco Ospedale Manzoni',
      patologia: 'Discopatia Lombare L4-L5 S1',
      titoloStudioLast: 'Diploma di Istituto Tecnico Industriale',
      anno: 1999,
      qualifica: 'Disegnatore Meccanico CAD / CAM',
      ecdl: 'Sì (Certificato PC)',
      stazioneEretta: false,
      movimentazioneManuale: false,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: false,
      contattoPubblico: false,
      impiegato: true,
      impiegatoMansione: 'Disegnatore CAD 2D/3D SolidWorks',
      disponibilita: {
        create: {
          orarioPreferito: 'Full-Time (40h)',
          smartWorking: true,
          raggioMaxKm: 25,
          mezzoMunit: true,
          noteDisponibilita: 'Mansione sedentaria a videoterminale con sedia ergonomica.'
        }
      }
    },
    {
      numeroIscrizione: 10465,
      codice: 'PERS-10465',
      nome: 'Marta',
      cognome: 'Galli',
      codiceFiscale: 'GLLMRT87S41E507D',
      dataNascita: new Date('1987-11-01'),
      natoA: 'Lecco',
      sesso: 'F',
      statoCivile: 'Celibe/Nubile',
      comuneResidenza: 'Malgrate',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Fabbrichini 15',
      cellulare: '3456789012',
      email: 'marta.galli@libero.it',
      patente: 'B',
      categoria: 'C.O.',
      categoriaLg6869: 'Disabilità Uditiva Media',
      dataIscrizioneCO: new Date('2018-12-05'),
      attivoNonAttivo: 'Attivo',
      stato: 'Occupato (T.Det)',
      disponibile: 'Sì',
      operatore: 'CPI Lecco (M. Galli)',
      icPercentuale: 52,
      diagnosi: 'Ipoacusia neurosensoriale bilaterale con protesizzazione.',
      asl: 'ASST Lecco',
      patologia: 'Ipoacusia Neurosensoriale',
      titoloStudioLast: 'Diploma di Liceo Linguistico',
      anno: 2006,
      qualifica: 'Addetta Archivio Digitale / Data Entry',
      ecdl: 'Sì (Certificato PC)',
      inglese: true,
      tedesco: false,
      stazioneEretta: true,
      movimentazioneManuale: true,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: false,
      colonna: true,
      contattoPubblico: false,
      impiegato: true,
      receptionSegreteria: false,
      disponibilita: {
        create: {
          orarioPreferito: 'Part-Time Pomeriggio',
          smartWorking: true,
          raggioMaxKm: 15,
          mezzoMunit: true,
          noteDisponibilita: 'Preferenza per inserimento dati, fatturazione elettronica e gestione documentale.'
        }
      }
    },
    {
      numeroIscrizione: 10466,
      codice: 'PERS-10466',
      nome: 'Andrea',
      cognome: 'Pessina',
      codiceFiscale: 'PSSNDR72C15F133E',
      dataNascita: new Date('1972-03-15'),
      natoA: 'Merate',
      sesso: 'M',
      statoCivile: 'Coniugato/a',
      comuneResidenza: 'Missaglia',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Merlini 23',
      cellulare: '3339876541',
      patente: 'B, C',
      categoria: 'C.O.',
      categoriaLg6869: 'Disabilità Motoria Traumatica',
      dataIscrizioneCO: new Date('2015-05-18'),
      attivoNonAttivo: 'Attivo',
      stato: 'Disoccupato',
      disponibile: 'Sì',
      operatore: 'CPI Merate (E. Bianchi)',
      icPercentuale: 72,
      diagnosi: 'Esiti amputazione traumatica avambraccio sinistro con protesi funzionale.',
      asl: 'ASST Lecco Ospedale Mandic Merate',
      patologia: 'Amputazione Arto Superiore Sinistro',
      handicapL104: true,
      allegatiLg68: true,
      titoloStudioLast: 'Licenza Media Inferiore con Corsi Professionali',
      anno: 1986,
      qualifica: 'Addetto Logistica Leggera / Receptionist',
      stazioneEretta: true,
      movimentazioneManuale: false,
      manualitaFine: false,
      artiSuperiori: false,
      vista: true,
      udito: true,
      colonna: true,
      contattoPubblico: true,
      receptionSegreteria: true,
      impiegato: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Part-Time Mattina (20-25h)',
          raggioMaxKm: 20,
          mezzoMunit: true,
          noteDisponibilita: 'Idoneo per portineria, centralino, controllo accessi aziendali.'
        }
      }
    },
    {
      numeroIscrizione: 10467,
      codice: 'PERS-10467',
      nome: 'Valentina',
      cognome: 'Longhi',
      codiceFiscale: 'LNGVNT96T50E507F',
      dataNascita: new Date('1996-12-10'),
      natoA: 'Lecco',
      sesso: 'F',
      statoCivile: 'Celibe/Nubile',
      comuneResidenza: 'Colico',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Nazionale 44',
      cellulare: '3401234567',
      email: 'valentina.longhi96@gmail.com',
      patente: 'B',
      categoria: 'C.O.',
      categoriaLg6869: 'Diabete Mellito Tipo 1 con complicanze',
      dataIscrizioneCO: new Date('2021-09-14'),
      attivoNonAttivo: 'Attivo',
      stato: 'Disoccupato',
      disponibile: 'Sì',
      operatore: 'CPI Lecco (M. Galli)',
      icPercentuale: 50,
      diagnosi: 'Diabete mellito insulino-dipendente con necessità di orari pasti regolari.',
      asl: 'ASST Lecco',
      patologia: 'Diabete Mellito Tipo 1',
      titoloStudioLast: 'Laurea Triennale in Servizio Sociale',
      titoloStudioPresso: 'Università degli Studi di Milano Bicocca',
      votazione: '106/110',
      anno: 2019,
      qualifica: 'Assistente Sociale Junior / Operatrice di Comunità',
      ecdl: 'Sì (Certificato PC)',
      inglese: true,
      stazioneEretta: true,
      movimentazioneManuale: true,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: true,
      contattoPubblico: true,
      impiegato: true,
      socialeScuola: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Part-Time Mattina (25-30h)',
          smartWorking: true,
          raggioMaxKm: 25,
          mezzoMunit: true,
          disponibileTurni: false,
          noteDisponibilita: 'No turni notturni; garantiti orari regolari per somministrazione terapia.'
        }
      }
    },
    {
      numeroIscrizione: 10468,
      codice: 'PERS-10468',
      nome: 'Paolo',
      cognome: 'Magni',
      codiceFiscale: 'MGNPLA65M08F133G',
      dataNascita: new Date('1965-08-08'),
      natoA: 'Merate',
      sesso: 'M',
      statoCivile: 'Coniugato/a',
      comuneResidenza: 'Cernusco Lombardone',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Brianza 5',
      cellulare: '3381122339',
      patente: 'B',
      categoria: 'C.O.',
      categoriaLg6869: 'Disabilità Motoria e Vascolare',
      dataIscrizioneCO: new Date('2014-11-20'),
      attivoNonAttivo: 'Attivo',
      stato: 'Disoccupato',
      disponibile: 'Sì',
      operatore: 'CPI Merate (E. Bianchi)',
      icPercentuale: 68,
      diagnosi: 'Insufficienza venosa cronica severa arti inferiori con divieto assoluto stazione eretta fissa.',
      asl: 'ASST Lecco Ospedale Mandic',
      patologia: 'Insufficienza Venosa Cronica',
      handicapL104: false,
      titoloStudioLast: 'Diploma di Geometra',
      anno: 1984,
      qualifica: 'Preventivista Edile e Computi Metrici',
      ecdl: 'Sì (Certificato PC)',
      stazioneEretta: false,
      movimentazioneManuale: false,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: false,
      contattoPubblico: true,
      impiegato: true,
      impiegatoMansione: 'Preventivazione e Gestione Pratiche Edilizia',
      disponibilita: {
        create: {
          orarioPreferito: 'Part-Time Ridotto (15-20h)',
          smartWorking: true,
          raggioMaxKm: 15,
          mezzoMunit: true,
          noteDisponibilita: 'Consolidata esperienza tecnico-amministrativa in imprese di costruzioni e studi.'
        }
      }
    },
    {
      numeroIscrizione: 10469,
      codice: 'PERS-10469',
      nome: 'Giulia',
      cognome: 'Sala',
      codiceFiscale: 'SLAGLI98B45E507H',
      dataNascita: new Date('1998-02-05'),
      natoA: 'Lecco',
      sesso: 'F',
      statoCivile: 'Celibe/Nubile',
      comuneResidenza: 'Lecco',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Amendola 2',
      cellulare: '3490011223',
      email: 'giulia.sala.graphic@gmail.com',
      patente: 'B',
      categoria: 'C.O.',
      categoriaLg6869: 'Disturbo dello Spettro Autistico Lieve (Asperger)',
      dataIscrizioneCO: new Date('2022-04-12'),
      attivoNonAttivo: 'Attivo',
      stato: 'In Tirocinio',
      disponibile: 'Sì',
      operatore: 'CPI Lecco (R. Rossi)',
      icPercentuale: 60,
      diagnosi: 'Sindrome di Asperger con eccellenti capacità logico-analitiche e focalizzazione visiva.',
      asl: 'ASST Lecco NPI / CPS',
      patologia: 'Disturbo Spettro Autistico Livello 1',
      handicapL104: true,
      allegatiLg68: true,
      titoloStudioLast: 'Diploma Istituto d\'Arte e Grafica Multimediale',
      anno: 2017,
      qualifica: 'Grafica Pubblicitaria e Web Designer',
      ecdl: 'Sì (Certificato PC)',
      inglese: true,
      stazioneEretta: true,
      movimentazioneManuale: true,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: true,
      contattoPubblico: false,
      impiegato: true,
      informatica: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Part-Time Mattina (20-25h)',
          smartWorking: true,
          raggioMaxKm: 20,
          mezzoMunit: true,
          noteDisponibilita: 'Altissima precisione su Photoshop, Illustrator, impaginazione e modellazione.'
        }
      }
    },
    {
      numeroIscrizione: 10470,
      codice: 'PERS-10470',
      nome: 'Fabio',
      cognome: 'Rigamonti',
      codiceFiscale: 'RGMFBA79R12A745I',
      dataNascita: new Date('1979-10-12'),
      natoA: 'Calolziocorte',
      sesso: 'M',
      statoCivile: 'Coniugato/a',
      comuneResidenza: 'Olginate',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Cantù 19',
      cellulare: '3358899001',
      patente: 'B',
      categoria: 'C.O.',
      categoriaLg6869: 'Disabilità Metabolica e Renale',
      dataIscrizioneCO: new Date('2019-07-25'),
      attivoNonAttivo: 'Attivo',
      stato: 'Disoccupato',
      disponibile: 'Sì',
      operatore: 'CPI Lecco (M. Galli)',
      icPercentuale: 75,
      diagnosi: 'Insufficienza renale cronica in trattamento emodialitico trisettimanale.',
      asl: 'ASST Lecco Ospedale Manzoni',
      patologia: 'Insufficienza Renale Cronica',
      handicapL104: true,
      allegatiLg68: true,
      titoloStudioLast: 'Diploma Tecnico Commerciale',
      anno: 1998,
      qualifica: 'Addetto Ufficio Personale e Paghe',
      ecdl: 'Sì (Certificato PC)',
      stazioneEretta: false,
      movimentazioneManuale: false,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: true,
      contattoPubblico: true,
      impiegato: true,
      impiegatoMansione: 'Amministrazione del Personale e Rilevazione Presenze',
      disponibilita: {
        create: {
          orarioPreferito: 'Part-Time Ridotto (15-20h)',
          smartWorking: true,
          raggioMaxKm: 20,
          mezzoMunit: true,
          noteDisponibilita: 'Disponibilità nei giorni non coincidenti con dialisi (martedì, giovedì, sabato).'
        }
      }
    },
    {
      numeroIscrizione: 10471,
      codice: 'PERS-10471',
      nome: 'Elisa',
      cognome: 'Cattaneo',
      codiceFiscale: 'CTTLSE91C55F133L',
      dataNascita: new Date('1991-03-15'),
      natoA: 'Merate',
      sesso: 'F',
      statoCivile: 'Celibe/Nubile',
      comuneResidenza: 'Lomagna',
      residenzaProvincia: 'LC',
      indirizzo: 'Via Milano 8',
      cellulare: '3473344556',
      email: 'elisa.cattaneo@gmail.com',
      patente: 'B',
      categoria: 'BSL',
      categoriaLg6869: 'BSL Borsa Lavoro / Tirocinio Inclusivo',
      dataIscrizioneCO: new Date('2023-01-15'),
      attivoNonAttivo: 'Attivo',
      stato: 'In Tirocinio',
      disponibile: 'Sì',
      operatore: 'CPI Merate (E. Bianchi)',
      icPercentuale: 65,
      diagnosi: 'Lieve ritardo psicomotorio con buone abilità pratiche e di socializzazione.',
      asl: 'ASST Lecco Ospedale Mandic Merate',
      patologia: 'Ritardo Cognitivo Lieve',
      handicapL104: true,
      allegatiLg68: true,
      titoloStudioLast: 'Attestato di Competenze Professionali C.F.P.',
      anno: 2011,
      qualifica: 'Ausiliaria di Mensa / Addetta Ristorazione e Accoglienza',
      stazioneEretta: true,
      movimentazioneManuale: false,
      manualitaFine: true,
      artiSuperiori: true,
      vista: true,
      udito: true,
      colonna: true,
      contattoPubblico: true,
      cassa: true,
      pulizie: true,
      socialeScuola: true,
      disponibilita: {
        create: {
          orarioPreferito: 'Part-Time Mattina (20-25h)',
          raggioMaxKm: 10,
          mezzoMunit: true,
          noteDisponibilita: 'Persona solare, puntuale ed entusiasta nelle mansioni ausiliarie e di supporto.'
        }
      }
    }
  ];

  for (const p of ventiPersone) {
    const { disponibilita, ...personaData } = p;
    await prisma.persona.upsert({
      where: { codiceFiscale: p.codiceFiscale },
      update: {
        ...personaData,
        disponibilita: disponibilita ? {
          upsert: {
            create: disponibilita.create,
            update: disponibilita.create
          }
        } : undefined
      },
      create: {
        ...personaData,
        disponibilita: disponibilita
      }
    });
  }

  // 2. Inserimento Utenze e Operatori di Sistema
  const defaultUsers = [
    {
      username: 'admin',
      email: 'admin.cpi@provincia.lecco.it',
      password: 'admin',
      nomeCompleto: 'Marco Galli',
      ruolo: 'ADMIN',
      sedeCpi: 'Lecco Centro',
      attivo: true
    },
    {
      username: 'elena.bianchi',
      email: 'elena.bianchi@provincia.lecco.it',
      password: 'password123',
      nomeCompleto: 'Elena Bianchi',
      ruolo: 'OPERATORE_SILV',
      sedeCpi: 'Merate',
      attivo: true
    },
    {
      username: 'roberto.rossi',
      email: 'roberto.rossi@provincia.lecco.it',
      password: 'password123',
      nomeCompleto: 'Roberto Rossi',
      ruolo: 'TUTOR_L68',
      sedeCpi: 'Lecco Nord',
      attivo: true
    },
    {
      username: 'anna.verdi',
      email: 'anna.verdi@asst-lecco.it',
      password: 'password123',
      nomeCompleto: 'Dott.ssa Anna Verdi',
      ruolo: 'ASL_MEDICO',
      sedeCpi: 'ASST Lecco Ospedale Manzoni',
      attivo: true
    }
  ];

  for (const u of defaultUsers) {
    await prisma.user.upsert({
      where: { username: u.username },
      update: {},
      create: u
    });
  }

  console.log(`✅ Database popolato con successo con ${ventiPersone.length} persone e ${defaultUsers.length} utenti attivi.`);
}

main()
  .catch((e) => {
    console.error('❌ Errore durante il seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
